name: call-cicd-windows-form

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-windows-form:
    uses: ./.github/workflows/cicd-windows-form-reusable.yaml
    with:
      test-directory: 'src/UnitTestProject1'
      app-directory: 'src/WindowsFormsApp-ok'
      artifacts-directory: 'src/WindowsFormsApp-ok/bin/Release/'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: write