name: Build Windows Forms App

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup MSBuild
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.3.1

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore
        working-directory: ${{ inputs.working-directory }}/WindowsFormsApp-ok

      # Build the project
      - name: Build the project
        run: msbuild /p:Configuration=Release
        working-directory: ${{ inputs.working-directory }}/WindowsFormsApp-ok

      # Cache ?

      - name: Install SonarScanner for MSBuild
        run: |
          choco install sonarscanner-msbuild -y
          refreshenv

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          SonarScanner.MSBuild.exe begin /k:"Gabriela-M-S1lva_Projeto-Windows-Form" /o:"gabriela-m-silva" /d:sonar.login="${SONAR_TOKEN}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build solution
        run: |
          msbuild.exe ${{ inputs.working-directory }}/WindowsFormsApp-ok/WindowsFormsApp-ok.sln /t:Rebuild

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          SonarScanner.MSBuild.exe end /d:sonar.login="${SONAR_TOKEN}"
  
  tests:
    runs-on: windows-latest
    needs: build
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup MSBuild
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.3.1

      # Setup VSTest
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      # Run tests
      - name: Run tests
        run: |
          vstest.console.exe **\bin\Debug\*Test*.dll --logger:trx
        working-directory: ${{ inputs.working-directory }}

