name: Build Windows Forms App

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup MSBuild
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.3.1

      # Download SonarScanner for MSBuild
      - name: Download SonarScanner for MSBuild
        run: |
          Invoke-WebRequest https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/10.1.2.114627/sonar-scanner-10.1.2.114627-net-framework.zip -OutFile scanner.zip
          Expand-Archive scanner.zip -DestinationPath $env:USERPROFILE\sonarscanner
          echo "$env:USERPROFILE\sonarscanner\sonar-scanner-msbuild-net46" | Out-File -Append -FilePath $env:GITHUB_PATH
        shell: powershell

      # Begin Sonar Analysis
      - name: Begin SonarCloud analysis
        run: |
          SonarScanner.MSBuild.exe begin `
            /k:"Gabriela-M-Silva_Projeto-Windows-Form" `
            /o:"gabriela-m-silva" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        working-directory: ${{ inputs.working-directory }}/WindowsFormsApp-ok
        shell: powershell

      # Restore NuGet
      - name: Restore NuGet packages
        run: nuget restore
        working-directory: ${{ inputs.working-directory }}/WindowsFormsApp-ok

      # Build
      - name: Build the project
        run: msbuild /p:Configuration=Release
        working-directory: ${{ inputs.working-directory }}/WindowsFormsApp-ok

      # End Sonar Analysis
      - name: End SonarCloud analysis
        run: SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        working-directory: ${{ inputs.working-directory }}/WindowsFormsApp-ok
        shell: powershell

  tests:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Run tests
        run: |
          vstest.console.exe **\bin\Debug\*Test*.dll --logger:trx
        working-directory: ${{ inputs.working-directory }}

